development: &default
  adapter: postgresql
  database: Surveyor_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  username:   
  password: 

test:
  <<: *default
  database: Surveyor_test
