default: &default
  # MORE THAN LIKELY WE DO NOT REALLY WANT OUR SECRET KEY JUST HANGING OUT
  secret_key_base: edf411b23bce0fe6c47a45b7ee783b68b4b9a36e928645f00107a34af6484913bdccfd279d26a508242f137bcf224b51d4a9637e9ffce21e3e36ccf3b5642781

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
