module DemographicHelper
  def gender
    [
      [],
      ['Female'],
      ['Male'],
      ['Other'],
    ]
  end
  def r_gender
    [
      [],
      ['Female'],
      ['Male'],
      ['Other'],
      ['Any'],
    ]
  end
  
  def education
    [
      [],
      ['High School or GED'],
      ['Associates Degree'],
      ["Bachelor Degree"],
      ["Master Degree"],
      ["Advanced"]
    ]
  end
  def r_education
    [
      [],
      ['High School or GED'],
      ['Associates Degree'],
      ["Bachelor Degree"],
      ["Master Degree"],
      ["Advanced"],
      ["Any"],
    ]
  end
  def nations
 
    [
        [],
        ['USA'],
        ['Afghanistan'],
        ['Albania'],
        ['Argentina'],
        ['Australia'],
        ['Bahrain'],
        ['Belarus'],
        ['Bhutan'],
        ['Brazil'],
        ['Cambodia'],
        ['Chile'],
        ['China'],
        ['Costa Rica'],
        ['Cuba'],
        ['Curacao'],
        ['Denmark'],
        ['Ecuador'],
        ['Egypt'],
        ['El Salvador'],
        ['Fiji'],
        ['Finland'],
        ['France'],
        ['Georgia'],
        ['Germany'],
        ['Greece'],
        ['Guatemala'],
        ['Haiti'],
        ['Honduras'],
        ['Hungary'],
        ['Iceland'],
        ['India'],      
        ['Indonesia'],
        ['Iran'],
        ['Iraq'],
        ['Ireland'],
        ['Israel'],
        ['Italy'],
        ['Japan'],
        ['Jordan'],
        ['Kazakhstan'],
        ['Kenya'],
        ['Kuwait'],
        ['Mexico'],
        ['Monaco'],
        ['Mongolia'],
        ['Nepal'],
        ['New Zealand'],
        ['Norway'],
        ['Qatar'],
        ['Russia'],
        ['Switzerland'],
        ['Sweden'],
        ['Taiwan'],
        ['United Kingdom'],
        ['United Arab Emirates'],
        ['Vietnam']
        ]
        end
    def r_nations
 
    [
        [],
        ['Any'],
        ['USA'],
        ['Afghanistan'],
        ['Albania'],
        ['Argentina'],
        ['Australia'],
        ['Bahrain'],
        ['Belarus'],
        ['Bhutan'],
        ['Brazil'],
        ['Cambodia'],
        ['Chile'],
        ['China'],
        ['Costa Rica'],
        ['Cuba'],
        ['Curacao'],
        ['Denmark'],
        ['Ecuador'],
        ['Egypt'],
        ['El Salvador'],
        ['Fiji'],
        ['Finland'],
        ['France'],
        ['Georgia'],
        ['Germany'],
        ['Greece'],
        ['Guatemala'],
        ['Haiti'],
        ['Honduras'],
        ['Hungary'],
        ['Iceland'],
        ['India'],      
        ['Indonesia'],
        ['Iran'],
        ['Iraq'],
        ['Ireland'],
        ['Israel'],
        ['Italy'],
        ['Japan'],
        ['Jordan'],
        ['Kazakhstan'],
        ['Kenya'],
        ['Kuwait'],
        ['Mexico'],
        ['Monaco'],
        ['Mongolia'],
        ['Nepal'],
        ['New Zealand'],
        ['Norway'],
        ['Qatar'],
        ['Russia'],
        ['Switzerland'],
        ['Sweden'],
        ['Taiwan'],
        ['United Kingdom'],
        ['United Arab Emirates'],
        ['Vietnam']
        ]
        end
      end
